spring:
  application:
    name: springcloudzuul
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait:
        max-idle: 8
        min-idle: 0
    timeout:
    password:
server:
  port: 8788
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8761/eureka/
zuul:
  add-host-header: true  #防止跳转到上游服务
  routes:
    user:
      path: /user/**
      serviceId: springclientuser
      sensitiveHeaders:
        - Authorization
      stripPrefix: false
    article:
      path: /article/**
      serviceId: springclientarticle
      sensitiveHeaders:
        - Authorization
      stripPrefix: false